import React from 'react';
import { Lightbulb, TrendingUp, TrendingDown, ShieldAlert, CheckCircle, Target, Award, ExternalLink } from 'lucide-react';

export default function StrategicView({ insights = [], deltas = [], records = [] }) {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* Top Banner */}
      <div className="glass-panel" style={{ padding: '20px 24px' }}>
        <h2 style={{ fontSize: '18px', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Target size={20} color="var(--amber-primary)" />
          Strategic Market Intelligence & Positioning
        </h2>
        <p style={{ fontSize: '13px', color: 'var(--text-secondary)', marginTop: '4px' }}>
          Corroborated market signals generated by StrategistAgent with mandatory ≥2-source verification.
        </p>
      </div>

      {/* Strategic Recommendations Grid */}
      <div>
        <h3 style={{ fontSize: '15px', fontWeight: 700, marginBottom: '14px', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Award size={16} color="var(--cyan-primary)" />
          Actionable Executive Recommendations ({insights.length})
        </h3>

        {insights.length === 0 ? (
          <div className="glass-panel" style={{ padding: '36px', textAlign: 'center', color: 'var(--text-muted)' }}>
            No strategic recommendations recorded yet. Run the pipeline to synthesize recommendations.
          </div>
        ) : (
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))', gap: '16px' }}>
            {insights.map((insight, idx) => (
              <div 
                key={idx}
                className="glass-panel"
                style={{
                  padding: '20px',
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'space-between',
                  gap: '14px',
                  borderLeft: '4px solid var(--amber-primary)',
                }}
              >
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '8px' }}>
                    <span className="badge badge-amber" style={{ fontSize: '10px' }}>
                      {insight.category || 'POSITIONING'}
                    </span>
                    <span className="badge badge-emerald" style={{ fontSize: '10px' }}>
                      <CheckCircle size={10} /> {insight.corroboration_count || 2} Sources Verified
                    </span>
                  </div>

                  <h4 style={{ fontSize: '15px', fontWeight: 700, color: 'var(--text-primary)', marginBottom: '8px' }}>
                    {insight.title}
                  </h4>

                  <p style={{ fontSize: '13px', color: 'var(--text-secondary)', lineHeight: 1.5, marginBottom: '12px' }}>
                    {insight.rationale}
                  </p>

                  <div style={{
                    background: 'rgba(0, 240, 255, 0.05)',
                    border: '1px solid rgba(0, 240, 255, 0.2)',
                    borderRadius: 'var(--radius-sm)',
                    padding: '10px 12px',
                  }}>
                    <span style={{ fontSize: '10px', textTransform: 'uppercase', fontWeight: 700, color: 'var(--cyan-primary)' }}>
                      Actionable Next Step:
                    </span>
                    <p style={{ fontSize: '12px', color: 'var(--text-primary)', marginTop: '2px', fontWeight: 500 }}>
                      {insight.actionable_next_step}
                    </p>
                  </div>
                </div>

                {/* Corroborating Sources Footer */}
                {(insight.corroborating_sources || []).length > 0 && (
                  <div style={{
                    paddingTop: '10px',
                    borderTop: '1px solid var(--border-subtle)',
                    fontSize: '11px',
                    color: 'var(--text-muted)',
                  }}>
                    <span style={{ fontWeight: 600 }}>Corroborating Sources: </span>
                    {insight.corroborating_sources.join(', ')}
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>

      {/* Historical Market Deltas */}
      <div>
        <h3 style={{ fontSize: '15px', fontWeight: 700, marginBottom: '14px', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <TrendingUp size={16} color="var(--violet-primary)" />
          Pricing & Feature Trend Deltas
        </h3>

        {deltas.length === 0 ? (
          <div className="glass-panel" style={{ padding: '24px', textAlign: 'center', color: 'var(--text-muted)', fontSize: '13px' }}>
            No price change deltas detected yet. Delta detection triggers automatically across successive pipeline runs.
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
            {deltas.map((delta, dIdx) => (
              <div 
                key={dIdx}
                className="glass-panel"
                style={{
                  padding: '14px 20px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  gap: '14px',
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
                  <div style={{
                    width: '32px',
                    height: '32px',
                    borderRadius: '8px',
                    background: delta.delta_type === 'PRICE_DROP' ? 'rgba(16, 185, 129, 0.1)' : 'rgba(239, 68, 68, 0.1)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                  }}>
                    {delta.delta_type === 'PRICE_DROP' ? (
                      <TrendingDown size={18} color="var(--emerald-primary)" />
                    ) : (
                      <TrendingUp size={18} color="var(--crimson-primary)" />
                    )}
                  </div>
                  <div>
                    <h5 style={{ fontSize: '13px', fontWeight: 700 }}>
                      {delta.company_name} — {delta.product_name}
                    </h5>
                    <p style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
                      {delta.summary || `${delta.field_changed}: ${delta.old_value} → ${delta.new_value}`}
                    </p>
                  </div>
                </div>

                <span className={`badge ${delta.delta_type === 'PRICE_DROP' ? 'badge-emerald' : 'badge-crimson'}`} style={{ fontSize: '10px' }}>
                  {delta.delta_type}
                </span>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
