"""Scrybe Core Domain Models and State Schemas.

All agents communicate across typed Pydantic models enforcing strict
zero-hallucination constraints, provenance tracking, and compliance.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, HttpUrl


class ScrapeTier(str, Enum):
    """Network scraping tier escalation levels."""
    TIER1_HTTPX = "httpx"
    TIER2_CURL_CFFI = "curl_cffi"
    TIER3_PLAYWRIGHT = "playwright"


class SourceTargetConfig(BaseModel):
    """Configuration for an ingested target source domain."""
    id: str = Field(description="Unique source ID, e.g. 'anthropic_pricing'")
    company_name: str
    target_url: str
    category: str = Field(default="LLM_INFERENCE")
    preferred_tier: ScrapeTier = Field(default=ScrapeTier.TIER1_HTTPX)
    selector_hints: Optional[List[str]] = Field(default_factory=list)
    check_frequency: str = Field(default="weekly")
    enabled: bool = True


class ComplianceAuditRecord(BaseModel):
    """Immutable audit record logged by the Compliance Agent."""
    audit_id: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    source_url: str
    robots_checked: bool = True
    robots_allowed: bool = True
    crawl_delay_applied_seconds: float = 2.5
    pii_scrubbed_count: int = 0
    login_bypass_attempted: bool = False
    compliance_status: str = Field(default="APPROVED")  # APPROVED | BLOCKED_BY_ROBOTS | SUSPICIOUS
    agent_version: str = "ScrybeComplianceGuard/v1.0"


class RawScrapedDocument(BaseModel):
    """Ingested document captured by the Reader Agent."""
    url: str
    domain: str
    status_code: int
    content_markdown: str
    content_hash: str
    scraped_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    scrape_tier_used: ScrapeTier
    pii_redacted: bool = True
    robots_compliant: bool = True


class PricingTier(BaseModel):
    """Granular pricing tier extracted from public pages."""
    model_or_tier_name: str
    input_price_per_m_tokens: Optional[float] = Field(
        default=None,
        description="USD per 1M input tokens. Must be null if not explicitly on page."
    )
    output_price_per_m_tokens: Optional[float] = Field(
        default=None,
        description="USD per 1M output tokens. Must be null if not explicitly on page."
    )
    cache_read_price_per_m_tokens: Optional[float] = Field(
        default=None,
        description="USD per 1M cached prompt tokens if supported."
    )
    context_window_tokens: Optional[int] = Field(
        default=None,
        description="Maximum supported context window in tokens."
    )
    fixed_monthly_price: Optional[float] = Field(
        default=None,
        description="Fixed monthly platform fee if applicable."
    )
    currency: Optional[str] = Field(default="USD")
    notable_features: List[str] = Field(default_factory=list)


class CompetitorProductRecord(BaseModel):
    """Normalized competitor profile extracted by Analyst Agent."""
    company_name: str
    product_name: str
    source_url: str
    pricing_tiers: List[PricingTier] = Field(default_factory=list)
    enterprise_terms_mentioned: bool = False
    rate_limits_summary: Optional[str] = None
    extraction_confidence: float = Field(ge=0.0, le=1.0)
    citation_text: str = Field(description="Exact snippet from source proving values")
    extracted_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class DeltaType(str, Enum):
    """Categorization of competitor changes."""
    PRICE_DECREASE = "PRICE_DECREASE"
    PRICE_INCREASE = "PRICE_INCREASE"
    NEW_TIER = "NEW_TIER"
    TIER_REMOVED = "TIER_REMOVED"
    FEATURE_ADDED = "FEATURE_ADDED"


class TrendDelta(BaseModel):
    """Calculated difference between current and historical records."""
    competitor_name: str
    product_name: str
    delta_type: DeltaType
    metric_name: str
    old_value: Optional[str]
    new_value: str
    percentage_change: Optional[float] = None
    strategic_severity: str = Field(default="MEDIUM")  # LOW | MEDIUM | HIGH | CRITICAL


class StrategicRecommendation(BaseModel):
    """Strategic advice generated by Strategist Agent."""
    category: str = Field(description="PRICING | POSITIONING | PRODUCT_ROADMAP")
    title: str
    rationale: str
    actionable_next_step: str
    corroborating_sources: List[str] = Field(min_length=1)
    corroboration_count: int = Field(ge=1)


class ScrybeState(BaseModel):
    """Master pipeline state container passed sequentially across agents."""
    pipeline_id: str
    run_timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    target_vertical: str = "B2B_AI_DEVELOPER_PLATFORMS"
    
    # Ingestion & Compliance
    raw_scrapes: List[RawScrapedDocument] = Field(default_factory=list)
    compliance_audits: List[ComplianceAuditRecord] = Field(default_factory=list)
    
    # Analyst Output
    extracted_records: List[CompetitorProductRecord] = Field(default_factory=list)
    flagged_records: List[Dict[str, Any]] = Field(default_factory=list)
    
    # Strategist Output
    historical_deltas: List[TrendDelta] = Field(default_factory=list)
    strategic_insights: List[StrategicRecommendation] = Field(default_factory=list)
    
    # Formatted Artifacts
    report_markdown: Optional[str] = None
    report_pdf_path: Optional[str] = None
    execution_metrics: Dict[str, Any] = Field(default_factory=dict)


class MarketIntelligenceReport(BaseModel):
    """Final published intelligence brief artifact."""
    report_id: str
    title: str
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    target_vertical: str
    executive_summary: str
    competitor_records: List[CompetitorProductRecord]
    market_deltas: List[TrendDelta]
    strategic_recommendations: List[StrategicRecommendation]
    citations: List[str]
